#!/bin/bash

# Important Notice

##########################################
# DON'T USE THAT, IT'S UNDER DEVELOPMENT #
##########################################

#
# filename: install-spfbl
#
export PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/sbin:/usr/local/bin

# SPFBL Server Setup

echo "----------------------------"
echo "Setting up SPFBL Server..."
echo "----------------------------"

# Checking if your system is CentOS/RedHat or Debian Based.
if [ -f /etc/redhat-release ]; then
    yum -y install wget
else
    apt-get install -y unzip wget
fi

# Download main distribution
wget https://github.com/leonamp/SPFBL/archive/master.zip

if [ -f master.zip ]; then
    unzip master.zip
    chmod +x SPFBL-master/*.sh
fi

# Move bash files to /etc
if [ ! -d /etc/spfbl ]; then
    mkdir -p /etc/spfbl
fi

# This command not will copy myself heh
mv SPFBL-master/*.sh /etc/spfbl

# Enable SPFBL autostart
mv /etc/spfbl/spfbl-startup.sh /etc/init.d/

if [ ! -f /etc/redhat-release ]; then
    update-rc.d spfbl-startup.sh defaults 100
fi
# Store SPFBL core to /opt
if [ ! -d /opt/spfbl ]; then
    mkdir -p /opt/spfbl
fi
mv SPFBL-master/dist /opt/spfbl

# Create log folder
if [ ! -d /var/log/spfbl ]; then
    mkdir -p /var/log/spfbl
fi

# Create .map folder
if [ ! -d /var/lib/spfbl ]; then
    mkdir -p /var/lib/spfbl
fi

# Make log rotation
mv SPFBL-master/logrotate/spfbl-rotate /etc/logrotate.d/spfbl

/etc/spfbl/spfbl-startup.sh

if [ "$(ps auxwf | grep SPFBL | wc -l)" -eq "1" ]; then
    echo "-------------------------------------------"
    echo "Done. Your SPFBL Server should almost UP!"
    echo "-------------------------------------------"
else
    echo "Oops, something occurs!"
fi

#end
