#!/bin/bash

# Important Notice

##########################################
#             Install SPFBL              #
##########################################

#
# filename: install-spfbl
#
export PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/sbin:/usr/local/bin
. /etc/init.d/functions

# SPFBL Server Setup
if [ "$1" == "--uninstall" ]; then
    echo "----------------------------"
    echo "Setting down SPFBL Server..."
    echo "----------------------------"
    echo "SHUTDOWN" | nc 127.0.0.1 9875
    rm -rf /opt/spfbl
    rm -rf /etc/spfbl
    rm -rf /usr/src/SPFBL
    rm -rf /etc/logrotate.d/spfbl
    rm -rf /var/log/spfbl
    rm -rf /etc/init.d/spfbl
else
    echo "----------------------------"
    echo "Setting up SPFBL Server..."
    echo "----------------------------"
    cd /usr/src
    echo "Entering $PWD folder... "
    echo
    echo -n "Installing git, nc, wget, unzip and java packages... "
    # Checking if your system is CentOS/RedHat or Debian Based.
    if [ -f /usr/bin/yum ]; then
        yum -y upgrade >/dev/null && yum -y install git nc unzip wget java-1.8.0-openjdk >/dev/null
        [ "$(rpm -q git java-1.8.0-openjdk wget unzip nc | wc -l)" -eq "5" ] && success || failure
        echo
    else
        apt-get update >/dev/null && apt-get install -y unzip wget git default-jre >/dev/null
    fi
    
    # Download main distribution
    if [ -d /usr/src/SPFBL ]; then
        echo -n "You have another spfbl into $PWD. Moving to $PWD/SPFBL.old.. "
        mv /usr/src/SPFBL /usr/src/SPFBL.old
        [ -d /usr/src/SPFBL.old ] && success || failure
        echo
    fi
    cd /usr/src && git clone https://github.com/leonamp/SPFBL.git
    echo -n "Cloning SPFBL into Github... "
    [ -d /usr/src/SPFBL ] && success || failure
    echo
    
    if [ -d /usr/src/SPFBL ]; then
        chmod +x SPFBL/client/*.sh
        chmod +x SPFBL/run/*
    fi
    
    # Move bash files to /etc
    if [ ! -d /etc/spfbl ]; then
        echo -n "Creating /etc/spfbl .. "
        mkdir -p /etc/spfbl
        cp SPFBL/client/*.sh /etc/spfbl/
        ln -sf /etc/spfbl/spfbl.sh /usr/local/bin/spfbl
        [ -d /etc/spfbl ] && success || failure
        echo
    fi
    
    # Create spfbl folder
    if [ ! -d /opt/spfbl ]; then
        echo -n "Creating /opt/spfbl .. "
        mkdir -p /opt/spfbl/bin
        cp SPFBL/run/spfbl-init.sh /opt/spfbl/bin/
        # Store SPFBL core to /opt
        cp SPFBL/dist/* /opt/spfbl/
        cp SPFBL/run/spfbl.conf /opt/spfbl/
        cp SPFBL/lib /opt/spfbl/
        cp SPFBL/data /opt/spfbl/
        cp SPFBL/doc /opt/spfbl/
        cp SPFBL/README.md /opt/spfbl/doc/
        [ -d /opt/spfbl ] && success || failure
        echo
    fi
    
    # Create log folder
    if [ ! -d /var/log/spfbl ]; then
        echo -n "Creating /var/log/spfbl .. "
        mkdir -p /var/log/spfbl
        [ -d /var/log/spfbl ] && success || failure
        echo
    fi
    
    # Enable SPFBL autostart
    if [ -f /etc/redhat-release ]; then
        echo -n "Installing spfbl into /etc/init.d .. "
        cp SPFBL/run/spfbl-init-centos /etc/init.d/spfbl
        chkconfig --add spfbl
        chkconfig spfbl on
        [ -f /etc/init.d/spfbl ] && success || failure
        echo
    else
        update-rc.d spfbl.sh defaults 100
    fi
    
    # Make log rotation
    echo -n "Installing spfbl into /etc/logrotate.d .. "
    cp SPFBL/run/spfbl-rotate /etc/logrotate.d/spfbl
    [ -f /etc/logrotate.d/spfbl ] && success || failure
    echo
    
    if [ -f /etc/redhat-release ] && [ -f /etc/init.d/spfbl ]; then
        service spfbl start
    else
        /opt/spfbl/bin/spfbl-init.sh start
    fi
    
    if [ "$(ps auxwf | grep SPFBL | grep -v grep | wc -l)" -eq "1" ]; then
        echo "-------------------------------------------"
        echo "Done. Your SPFBL Server should almost UP!"
        echo "-------------------------------------------"
    else
        echo "Oops, something occurs!"
    fi
fi

#end
