#!/bin/bash

# Important Notice

##########################################
# DON'T USE THAT, IT'S UNDER DEVELOPMENT #
##########################################

#
# filename: install-spfbl
#
export PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/sbin:/usr/local/bin

# SPFBL Server Setup

echo "----------------------------"
echo "Setting up SPFBL Server..."
echo "----------------------------"

# Checking if your system is CentOS/RedHat or Debian Based.
if [ -f /usr/bin/yum ]; then
    yum -y upgrade >/dev/null && yum -y install nc unzip wget java-1.8.0-openjdk
else
    apt-get update >/dev/null && apt-get install -y unzip wget default-jre
fi

# Download main distribution
wget https://github.com/leonamp/SPFBL/archive/master.zip

if [ -f master.zip ]; then
    unzip master.zip
    chmod +x SPFBL-master/client/*.sh
    chmod +x SPFBL-master/run/*
fi

# Move bash files to /etc
if [ ! -d /etc/spfbl ]; then
    mkdir -p /etc/spfbl
    mv SPFBL-master/client/*.sh /etc/spfbl/
    ln -sf /etc/spfbl/spfbl.sh /usr/local/bin/spfbl
fi

# Create spfbl folder
if [ ! -d /opt/spfbl ]; then
    mkdir -p /opt/spfbl/bin
    mv SPFBL-master/run/spfbl-init.sh /opt/spfbl/bin/
    # Store SPFBL core to /opt
    mv SPFBL-master/dist/* /opt/spfbl/
    mv SPFBL-master/data /opt/spfbl/
    mv SPFBL-master/doc /opt/spfbl/
    mv SPFBL-master/README.md /opt/spfbl/doc/
fi

# Create log folder
if [ ! -d /var/log/spfbl ]; then
    mkdir -p /var/log/spfbl
fi

# Enable SPFBL autostart
if [ -f /etc/redhat-release ]; then
    mv SPFBL-master/run/spfbl-init-centos /etc/init.d/spfbl
    chkconfig --add spfbl
    chkconfig spfbl on
else
    update-rc.d spfbl.sh defaults 100
fi

# Make log rotation
mv SPFBL-master/run/spfbl-rotate /etc/logrotate.d/spfbl

if [ -f /etc/redhat-release ]; then
    service spfbl start
else
    /opt/spfbl/bin/spfbl-init.sh start
fi

if [ "$(ps auxwf | grep SPFBL | grep -v grep | wc -l)" -eq "1" ]; then
    echo "-------------------------------------------"
    echo "Done. Your SPFBL Server should almost UP!"
    echo "-------------------------------------------"
else
    echo "Oops, something occurs!"
fi

#end
