#!/bin/bash

# chkconfig: 345 99 01
# description: SPFBL
. /etc/init.d/functions

start()
{
    ret=0
    echo -n "[SPFBL] Starting... "
    if [ "$(ps auxwf | grep java | grep SPFBL | grep -v grep | wc -l)" -eq "0" ]; then
        cd /opt/spfbl/
        # Log personalizado caso nao deseja utilizar logrotate.d/spfbl
        if [ ! -f /etc/logrotate.d/spfbl ]; then
            /usr/bin/java -jar -Xms512m -Xmx1536m /opt/spfbl/SPFBL.jar &
        else
            /usr/bin/java -jar -Xms512m -Xmx1536m /opt/spfbl/SPFBL.jar &
        fi
        ret=$(ps auxwf | grep java | grep SPFBL | grep -v grep | wc -l)
        if [ "$ret" -eq "0" ]; then
            echo -n "Error"
            ret=0
        fi
    else
       echo -n "Already started. "
       ret=0
    fi
    [ "$ret" -eq "1" ] && success || failure
    echo
}

stop()
{
    ret=1
    echo -n "[SPFBL] Stopping... "
    if [ "$(ps auxwf | grep java | grep SPFBL | grep -v grep | wc -l)" -eq "1" ]; then
        response=$(echo "SHUTDOWN" | nc 127.0.0.1 9875)
        sleep 3
        if [[ $response == "" ]]; then
            ret=1
        elif [[ $response == "OK" ]]; then
            ret=0
        fi
        ret=$(ps auxwf | grep java | grep SPFBL | grep -v grep | wc -l)
    else
       echo -n "Already stopped. "
       ret=1
    fi
    [ "$ret" -eq "0" ] && success || failure
    echo
}

restart()
{
    stop
    start
}

status()
{
    if [ "$(ps auxwf | grep java | grep SPFBL | grep -v grep | wc -l)" -eq "1" ]; then
        echo -n "[SPFBL] Server is running"
        success
        echo
        ps axwuf | grep -E "PID|SPFBL" | grep -v grep
    else
        echo -n "[SPFBL] Server is not running"
        echo
    fi
}

case "$1" in
    start)
        start
    ;;
    stop)
        stop
    ;;
    restart)
        restart
    ;;
    status)
        status
    ;;
esac
